swagger: "2.0"
info:
  description: This is the swagger UI with GET methods only. 
  version: "1.0.0"
  title: Swagger API
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /daily:
    get:
      operationId: fitapi.dailyInfo.read_all
      tags:
        - DailyInfo
      summary: Read the entire list of daily info for user
      description: Read the entire list of daily info for user
      responses:
        200:
          description: Successfully read user set operation
          schema:
            type: array
            items:
              properties:
                user_id:
                  type: integer
                  description: Id of the user
                fname:
                  type: string
                  description: First name of the person
                lname:
                  type: string
                  description: Last name of the person
                dates:
                  type: array
                  items:
                    properties:
                      user_id:
                        type: integer
                        description: Id of user this day is associated with
                      startDate:
                        type: string
                      endDate:
                        type: string
      
  /daily/{user_id}:
    get:
      operationId: fitapi.dailyInfo.read_one
      tags:
        - DailyInfo
      summary: Read one user
      description: Read one user
      parameters:
        - name: user_id
          in: path
          description: Id of the user to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read user from User data operation
          schema:
            type: object
            properties:
              user_id:
                type: string
                description: Id of the user
              fname:
                type: string
                description: First name of the user
              lname:
                type: string
                description: Last name of the user
              notes:
                type: array
                items:
                  properties:
                    user_id:
                      type: integer
                      description: Id of person this note is associated with
                    startDate:
                      type: string
                      description: start date
                    endDate:
                      type: string
                      description: end date

  /dates:
    get:
      operationId: fitapi.dates.read_all
      tags:
        - DailyInfo
      summary: Read the entire set of dates for all users
      description: Read the entire set of dates for all users
      responses:
        200:
          description: Successfully read dates for all users operation
          schema:
            type: array
            items:
              properties:
                startDate:
                  type: string
                  description: start date
                endDate:
                  type: string
                  description: end date
                user:
                  type: object
                  properties:
                    user_id:
                      type: integer
                      description: Id of associated user
                    fname:
                      type: string
                      description: Frist name of associated user
                    lname:
                      type: string
                      description: Last name of associated user

  /daily/{user_id}/date/{startDate}:
    get:
      operationId: fitapi.dates.read_one
      tags:
        - DailyInfo
      summary: Read a particular date associated with a user
      description: Read a particular date associated with a user
      parameters:
        - name: user_id
          in: path
          description: Id of user associated with date
          type: integer
          required: True
        - name: startDate
          in: path
          description: IMPORTANT :-  start date must be dd-mm-yyyy format
          type: string
          required: True
      responses:
        200:
          description: Successfully read date for a user
          schema:
            type: object
            properties:
              startDate:
                type: string
                description: IMPORTANT :-  start date must be dd-mm-yyyy format
              user_id:
                type: integer
                description: Id of the user note associated with
              endDate:
                type: string
                description: end date
     