swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Documentation
consumes:
  - "application/json" # may need to change this
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /daily:
    get:
      operationId: fitapi.dailyInfo.read_all # which module to call
      tags:
        - DailyInfo
      summary: Read the entire list of daily info for user
      description: Read the list of daily info
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of daily entries to get from dailyInfo
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering daily info
          required: false
      responses:
        200:
          description: Successfully read daily info list operation
          schema:
            type: array
            items:
              properties:
                daily_id:
                  type: string
                  description: Id of the date entry
                startDate:
                  type: string
                endDate:
                  type: string
    post:
      operationId: fitapi.dailyInfo.create
      tags:
        - DailyInfo
      summary: Create a daily entry and add it to the daily info list
      description: Create a new daily entry in the daily info list
      parameters:
        - name: day
          in: body
          description: Daily entry to create
          required: True
          schema:
            type: object
            properties:
              startDate:
                type: string
                description: start date
              endDate:
                type: string
                description: end date
      responses:
        201:
          description: Successfully created daily entry in list
          schema:
              properties:
                daily_id:
                  type: string
                  description: Id of the date entry
                startDate:
                  type: string
                endDate:
                  type: string

  /daily/{startDate}:
    get:
      operationId: fitapi.dailyInfo.read_one
      tags:
        - DailyInfo
      summary: Read one date from the daily info list
      description: Read one date from the daily info list
      parameters:
        - name: startDate
          in: path
          description: Date to get from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully read daily entry from daily info list
          schema:
            type: object
            properties:
              daily_id:
                type: string
                description: Id of the date entry
              startDate:
                type: string
              endDate:
                type: string

    put:
      operationId: fitapi.dailyInfo.update
      tags:
        - DailyInfo
      summary: Update/modify a daily entry in the daily info list
      description: Update/modify a daily entry in the daily info list
      parameters:
        - name: startDate
          in: path
          description: The date to be updated
          type: string
          required: True
        - name: day
          in: body
          schema:
            type: object
            properties:
              endDate:
                type: string
              startDate:
                type: string
      responses:
        200:
          description: Successfully updated daily entry in daily info list
          schema:
              properties:
                daily_id:
                  type: string
                  description: Id of the date entry
                startDate:
                  type: string
                endDate:
                  type: string


    delete:
      operationId: fitapi.dailyInfo.delete
      tags:
        - DailyInfo
      summary: Delete an entry from the daily info list
      description: Delete an entry from the daily info list
      parameters:
        - name: startDate
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted an entry from the daily info list   